language: cpp

compiler:
  - g++

before_script:
  - sudo apt remove cmake
  - curl https://cmake.org/files/v3.9/cmake-3.9.0-rc3.tar.gz > /tmp/cmake.tar.gz
  - mkdir build
  - cd build
  - cmake ..

script: make
