language: cpp

compiler:
  - g++

before_script:
  - $WORKSPACE=pwd
  - sudo apt remove cmake
  - curl https://cmake.org/files/v3.9/cmake-3.9.0-rc3.tar.gz > /tmp/cmake.tar.gz
  - cd /tmp; tar xvf cmake.tar.gz; cd cmake-3.9.0-rc3/; ./configure; make; sudo make install
  - curl -L "https://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.gz" > /tmp/boost.tar.gz
  - cd /tmp; tar xvf boost.tar.gz; cd boost_1_63_0/; ./bootstrap.sh --prefix=/usr/local; sudo ./b2 install
  - cd $WORKSPACE
  - mkdir build
  - cd build
  - cmake ..

script: make
